name: imeyou_tamagochi
description: Умный тамагочи помощник
version: 1.0.0+1
publish_to: 'none'


environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.5.1
  screen_retriever: ^0.2.0 
  screen_text_extractor: ^0.0.1
  universal_platform: ^1.1.0
  shared_preferences: ^2.2.2
  http: ^1.2.0
  url_launcher: ^6.2.3
  path_provider: ^2.1.1
  archive: ^3.4.2
  path: ^1.9.0
  desktop_drop: ^0.6.1
  bitsdojo_window: ^0.1.1+1
  file_icon: ^1.0.0
  file_picker: ^5.5.0
  system_theme: ^3.1.2
  ffi: ^2.0.1
  win32: 5.14.0
  clipboard: ^0.1.3
  # ДЛЯ РАБОТЫ С ИЗОБРАЖЕНИЯМИ И QR-КОДАМИ
  image_picker: ^1.0.4
  cross_file: ^0.3.3
  image: ^4.0.17
  # Для QR-кодов (альтернатива - более надежная)
  crypto: ^3.0.3
  # Для OCR (распознавания текста)
  screenshot: ^3.0.0
  google_mlkit_text_recognition: ^0.15.0
  desktop_screenshot: ^0.0.4
  flutter_colorpicker: ^1.0.3
  audioplayers: ^5.2.1
  speech_to_text: ^6.6.0  # или актуальная версия
  intl: ^0.18.1
  html: ^0.15.1
  cached_network_image: ^3.3.0
  universal_io: ^2.2.2
  encrypt: ^5.0.1
  charset_converter: ^2.0.3
  webview_flutter: ^4.13.0
  elliptic: ^0.3.12
  math_expressions: ^2.3.0
  process_run: ^0.12.0
  flutter_bloc: ^8.1.3
#  model_viewer_plus: ^1.0.1
#  flutter_cube: ^0.1.1

  webview_windows: ^0.3.0

  pointycastle: ^3.7.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/tessdata/
    - assets/models/pet5.glb
    - assets/models/